### ISSUE TITLE
是否是因为没有python开发环境

### ISSUE THREAD

**Issue by Tian0225** [YeYoot/batch_create_account#1]
![image](https://user-images.githubusercontent.com/23043061/56850361-1f8c1200-6934-11e9-9baf-445f58b38c53.png)

**Comment by YeYoot** [comment]
xlrd是一个读写excel的三方库，需要自己手动用pip安装一下

**Comment by YeYoot** [comment]
依次键入以下命令即可
sudo yum -y install epel-release
sudo yum -y install python-pip
pip install xlrd
pip install pexpect
