### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by damopelder** [YeYoot/batch_create_account#4]
其他的安装也是这样
有些么说安装python失败
已经不知道该怎么办了

**Comment by damopelder** [comment]
![图片1](https://user-images.githubusercontent.com/56266922/66548184-5c129980-eb73-11e9-86e6-0b845469e412.png)

**Comment by YeYoot** [comment]
> 其他的安装也是这样
> 有些么说安装python失败
> 已经不知道该怎么办了

服务器是选择的什么操作系统？确认一下是不是没有自带python?

**Comment by damopelder** [comment]
我解决了
在服务器那里的setting吧centos改成6或7就行了
vultr他那里默认是centos new 所以一直装不起来
网上的教程多半是因为这个原因装不起来
你可以吧这点补充一下

**Comment by YeYoot** [comment]
> 我解决了
> 在服务器那里的setting吧centos改成6或7就行了
> vultr他那里默认是centos new 所以一直装不起来
> 网上的教程多半是因为这个原因装不起来
> 你可以吧这点补充一下

嗯
